name: Backend Build

on:  
  workflow_call:  
    inputs:
      buildConfiguration:
        required: true
        type: string
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    #needs: InstallSonarScanner
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check for changes
        shell: bash
        id: changes
        run: |
          if [ -n "$(git diff HEAD HEAD^ -- './.github/')" ]; then
            echo "::set-output name=folder-updated::true"
          else
            echo "::set-output name=folder-updated::false"
          fi
      - name: Take action based on changes
        if: steps.changes.outputs.folder-updated == 'false'
        run: |
          echo "No files were changed in ./.github. Stopping workflow."
          exit 1
      - name: InstallSonarScanner
        uses: ./.github/actions/install-sonar-scanner
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.6
      - name: Restore NuGet packages
        run: nuget restore ./WebApplication1/WebApplication1.sln

        #Sonar


      #- name: Build
      #  run: msbuild ./WebApplication1/WebApplication1.sln /p:Configuration=${{ inputs.buildConfiguration }}

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"AnRimkus_BuildDotNetSonar" /o:"anrimkus" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          #<insert_your_clean_build_command>
          msbuild ./WebApplication1/WebApplication1.sln /p:Configuration=${{ inputs.buildConfiguration }}
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
