on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "closed" ]
  workflow_call:  
  workflow_dispatch:
  
jobs:
  build-be:
    secrets: inherit
    uses: ./.github/workflows/build-be.yml
    with:
      buildConfiguration: Release
